# Generated by Django 4.0.6 on 2022-07-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
